[package]
name = "innisfree"
version = "0.2.11"
authors = ["Conor Schaefer <conor@ruin.dev>"]
edition = "2018"
description = "Exposes local services on public IPv4 address, via cloud server."
license = "AGPL-3.0-only"
readme = "README.md"
publish = true
repository = "https://github.com/conorsch/innisfree"
categories = ["command-line-utilities", "network-programming"]
keywords = ["self-hosting", "wireguard"]

[dependencies]
clap = "3.0.0-beta.2"
custom_error = "~1.9"
env_logger = "~0.9"
futures = "0.3"
home = "~0.5"
ipnet = "~2"
log = "~0.4"
pnet = "~0.28"
rand = "~0.8"
reqwest = { version = "~0.11", features = ["json", "rustls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "~1"
serde_yaml = "~0.8"
tempfile = "3"
tera = "1"
tokio = { version = "~1.9", features = [ "io-util", "macros", "net", "rt-multi-thread", "signal"] }

[package.metadata.deb]
maintainer-scripts = "debian/"
# Not using auto-detection, since that creates distro dependencies.
# Building on Debian Bullseye workstation causes install failure
# for Debian Buster server, for example.
# depends = "$auto"
# Autogenerated deps were (on Buster):
# Depends: libssl1.1 (>= 1.1.1d), libc6 (>= 2.28)
depends = "libssl1.1 (>= 1.1.1d), libc6 (>= 2.28), libcap2-bin"
extended-description = "Creates a remote host in the cloud, then establishes a Wireguard tunnel to it. Only supports proxying TCP traffic, for now."
assets = [
  ["target/release/innisfree", "usr/bin/", "755"],
  ["innisfree@.service", "usr/lib/systemd/system/", "644"],
]
name = "innisfree"
priority = "optional"
section = "net"
