[package]
name = "innisfree"
version = "0.1.1"
authors = ["Conor Schaefer <conor.schaefer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
log = "0.4.0"
env_logger = "0.8.3"
