---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: innisfree
  namespace: innisfree
spec:
  replicas: 1
  selector:
    matchLabels:
      app: innisfree
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: innisfree
    spec:
      imagePullSecrets:
      - name: docker-registry-creds
      containers:
      - name: innisfree
        image: docker.ruin.dev/innisfree:latest
        imagePullPolicy: Always
        command:
          - /usr/bin/innisfree
        env:
        - name: INNISFREE_PROXY_ADDRESS
          value: ingress-nginx-controller.ingress-nginx
        - name: INNISFREE_LOCAL_PORT
          value: "80"
        - name: DIGITALOCEAN_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: innisfree-config
              key: digitalocean_api_token
        - name: DIGITALOCEAN_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: innisfree-config
              key: digitalocean_api_token
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          privileged: True
          capabilities:
            add:
              - NET_ADMIN
              - SYS_ADMIN
