---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: innisfree
    app.kubernetes.io/instance: innisfree
    app.kubernetes.io/version: 0.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: innisfree-controller
  namespace: innisfree
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: innisfree
    app.kubernetes.io/instance: innisfree
    app.kubernetes.io/component: controller
